### ISSUE TITLE
执行程序后报错。

### ISSUE THREAD

**Issue by just805** [ExpLangcn/Aopo#2]
执行的命令：Aopo_Windows_x86.exe -ip 192.168.1.1/24
详细说明遇到的问题：
执行程序后报错。
截图：
![123](https://user-images.githubusercontent.com/18697510/166235939-08781587-eb66-4eb1-b444-39156cb7355f.png)

环境信息
操作系统：Microsoft Windows 11 企业版
内核版本：21H2
程序版本：Aopo - V1.0.2

**Comment by ExpLangcn** [comment]
右键管理员允许CMD然后执行程序看看是否报错。

**Comment by just805** [comment]
> 管理员允许 CMD 然后执行程序查看是否报错。

就是用的管理员模式。

**Comment by ExpLangcn** [comment]
联系微信：backxyh 我看下

**Comment by ExpLangcn** [comment]
预计下个版本修复

**Comment by CaiNiao0** [comment]
同问题
